### ISSUE TITLE
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.

### ISSUE THREAD

**Issue by Lyndsey-Xing** [yfsong0709/RA-GCNv2#1]

**Comment by yfsong0709** [comment]
I dont know what you mean. But I think this link may help you.
https://github.com/pytorch/pytorch/issues/42327#event-3867660282
Something wrong in nn.ParameterList when PyTorch >= 1.4.0.
