### ISSUE TITLE
.tar file not found

### ISSUE THREAD

**Issue by tlqwd** [yfsong0709/RA-GCNv2#2]
When I run the program, the following error appears，I tried to open models / checkpoint.pth.tar and found that the file could not be opened.How can I solve this problem?
![Uploading %RAMS[1ELV%3CH@_V@JLDGT.png…]()

**Comment by yfsong0709** [comment]
Sorry, I can not see the picture. The checkpoint.pth.tar will be saved at 'workdir' folder after the first iteration. Hope this comment will help you.
